import type { ReactNode } from "react";
import { ogMetadata } from "~/lib/og";

export const metadata = ogMetadata(
  "Image",
  "Displays image content generated by language models.",
);

export default function Layout({ children }: { children: ReactNode }) {
  return children;
}
