"use client";

import type { GenerativeImageStates } from "@repo/ui";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import {
  GenerativeImage,
  GenerativeImageSkeleton,
  generativeImageStates,
} from "@repo/ui";
import { FaGithub } from "react-icons/fa";

import { StateToggle } from "../../components/state-toggle";

export default function ImagePage() {
  const [controlledState, setControlledState] = useState<
    GenerativeImageStates | undefined
  >("loading");
  const loadingTimeoutRef = useRef<NodeJS.Timeout | null>(null);
  const isManualChangeRef = useRef(false);

  // Handle automatic transition from loading to default after 4 seconds
  useEffect(() => {
    if (controlledState === "loading") {
      // Clear any existing timeout
      if (loadingTimeoutRef.current) {
        clearTimeout(loadingTimeoutRef.current);
      }

      // Set a new timeout to transition to default after 4 seconds
      loadingTimeoutRef.current = setTimeout(() => {
        setControlledState("default");
        isManualChangeRef.current = false;
      }, 4000);
    } else {
      // Clear timeout if state changes away from loading
      if (loadingTimeoutRef.current) {
        clearTimeout(loadingTimeoutRef.current);
      }
    }

    // Cleanup timeout on unmount or state change
    return () => {
      if (loadingTimeoutRef.current) {
        clearTimeout(loadingTimeoutRef.current);
      }
    };
  }, [controlledState]);

  const handleStateChange = (newState: GenerativeImageStates) => {
    // If this is a manual change (from toggle), ignore auto-transitions
    if (isManualChangeRef.current) {
      isManualChangeRef.current = false;
      return;
    }
    // Always update state from component (including hover/unhover)
    setControlledState(newState);
  };

  const handleManualStateChange = (newState: GenerativeImageStates) => {
    isManualChangeRef.current = true;
    setControlledState(newState);
  };

  return (
    <main className="flex min-h-screen flex-col items-center justify-start bg-[#101010] p-8">
      <div className="mt-8 relative">
        {controlledState === "loading" && (
          <div className="absolute inset-0">
            <GenerativeImageSkeleton width={400} height={400} />
          </div>
        )}
        <div
          className={
            controlledState === "loading"
              ? "opacity-0"
              : "opacity-100 transition-opacity duration-300"
          }
        >
          <GenerativeImage
            src="/abstract.png"
            alt="Abstract GLSL Shader"
            model="dall-e-3"
            width={400}
            height={400}
            controlledState={controlledState}
            onStateChange={handleStateChange}
          />
        </div>
      </div>
      <div className="mx-auto my-24 flex w-[650px] max-w-full flex-col justify-start">
        <p className="mb-2 text-sm font-light tracking-wide text-white">
          Generative Image
        </p>
        <p className="text-sm font-light tracking-wide text-[#888]">
          Displays image content generated by language models.
        </p>
        <hr className="my-16 border-[#333] border-opacity-50" />
        <div className="flex flex-row flex-wrap justify-between gap-16 text-white">
          <StateToggle
            states={generativeImageStates as readonly GenerativeImageStates[]}
            activeState={controlledState ?? "loading"}
            onStateChange={handleManualStateChange}
          />

          <div className="flex w-full flex-row-reverse items-center justify-end gap-4 tracking-wide md:w-fit md:flex-row">
            <span className="text-xs font-light">
              Built by <Link href={"https://x.com/danielsims"}>danielsims</Link>
            </span>
            <Link href={"https://github.com/danielsims/ui"}>
              <FaGithub className="fill-white text-white" size={24} />
            </Link>
          </div>
        </div>
      </div>
    </main>
  );
}
